- name: install and run nginx 
  hosts: web
  become: yes 
  Tasks:
    - name: install nginx
      ansible.bulitin.package;
        name: nginx
        state: present
    - name: run nginx
      ansible.bulitin.package;
        name: nginx
        state: started 